MainProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app_core.views import *
from app_core.admin_views import *


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", welcome_page, name="welcome-page"),
    path("admin_home", admin_home, name="admin-welcome-page"),
    path("login", login_page, name="login-page"),
    path("login_user", login_user, name="login-user"),
    path("logout_user", logout_page, name="logout-user"),
    path("register", register_page, name="register-user"),
    path("rooms", view_rooms, name="view-rooms"),
    path("app/", include("app_core.urls", namespace="app")),
    path('ajax/check-username/', check_username, name='check_username'),

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_core/urls.py
from django.contrib import admin
from django.urls import path
from .student_views import *
from app_core.admin_views import *


app_name = "app"


urlpatterns = [

    # Students Urls
    
    path("student_dashboard", student_dashboard, name = "student-dashboard"),
    path("student_register", student_register, name = "student-register"),
    path("room_details/<str:room_id>", room_details, name = "room-details"),
    path("payment", payment, name = "payment"),
    path("accomodation_request", accomodation_request, name = "accomodation-request"),
    path("room_transfer", room_transfer, name = "room-transfer"),
    path("guest_stay", guest_stay, name = "guest-stay"),
    path("complain", complaints, name = "complaints"),
    path('rents', view_rents, name='view-rents'),
    
    # Admin Urls

    path("create_block", create_block, name = "create-block"),
    path("create_manager", create_manager, name = "create-manager"),
    path("create_room", create_room, name = "create-room"),
    path("manage_request", manage_request, name = "manage-request"),
    path("manage_transfer", manage_transfer, name = "manage-transfer"),
    path("manage_guest", manage_guest, name = "manage-guest"),
    path("manage_complaints", manage_complaints, name = "manage-complaints"),
    path("manage_rule", manage_rule, name = "manage-rule"),
    path("approve_or_disapprove/<str:ac_id>", approve_or_disapprove, name = "approve_or_disapprove"),
    path("complain_status/<str:complain_id>", complain_status, name = "complain_status"),
    path("guest_status/<str:guest_id>", guest_status, name = "guest_status"),
    path("transfer_status/<str:transfer_id>", transfer_status, name = "transfer_status"),
    path("request_dashboard", request_dashboard, name = "request-dashboard"),
    

]

app_core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.template.defaultfilters import truncatechars

class Student_Account(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    matric = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    is_student = models.BooleanField(default = True)
    wallet = models.IntegerField(default = 0, null = True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.username


class Deposit(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 200)
    card_number = models.CharField(max_length=20)
    bank = models.CharField(max_length = 6)
    date_submit = models.CharField(max_length = 100)
    amount = models.IntegerField()
    confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def save(self, *args, **kwargs):
        if self.pk:  # Kiểm tra nếu khoản tiền gửi đã tồn tại
            old_deposit = Deposit.objects.get(pk=self.pk)
            if old_deposit.confirm is False and self.confirm is True:  # Xác nhận lần đầu
                self.student.wallet += self.amount
                self.student.save()
        super().save(*args, **kwargs)  # Gọi phương thức save "thật"

    def __str__(self):
        return self.student.user.username


class House_Manager(models.Model):
    full_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    phone_no = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name


class Block(models.Model):
    house_manager = models.ForeignKey(House_Manager, on_delete = models.CASCADE)
    block_name = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.block_name


class Rooms(models.Model):
    block = models.ForeignKey(Block, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=50, null=True)
    room_tag = models.CharField(max_length=10, default="NEW")
    description = models.TextField()
    condition = models.TextField()
    charge = models.IntegerField()
    slot_available = models.IntegerField(default=10) # tối đa 10 giường 
    is_available = models.BooleanField(default=True)
    image1 = models.ImageField(upload_to="photos")
    image2 = models.ImageField(upload_to="photos")
    image3 = models.ImageField(upload_to="photos")
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def short_description(self):
        return truncatechars(self.description, 20)
    def admin_photo(self):
        return mark_safe('<img src ="{}" width = 100 />'.format(self.image1.url))
    admin_photo.short_description = "Image"
    admin_photo.allow_tag = True
    def __str__(self):
        return self.room_name


class Accomodation_Request(models.Model):
    student = models.OneToOneField(Student_Account, on_delete = models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    approved = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)


    def __str__(self):
        return f"{self.room.room_name} has been {self.approved} {self.student.first_name}"



class Complaints(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.student.first_name} - {self.subject}"



class GuestStayRequest(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 40)
    address = models.CharField(max_length = 40)
    reason = models.TextField()
    status = models.BooleanField(default=False)
    date_from = models.DateField()
    date_to = models.DateField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.student.first_name} - {self.full_name}"


class RoomTransfer(models.Model):
    student = models.ForeignKey(Student_Account, on_delete=models.CASCADE)
    reason = models.TextField()
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE, related_name='new_room')  # phòng chuyển đến
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     # Lấy thông tin phòng hiện tại của sinh viên trước khi cập nhật
    #     accommodation_request = Accomodation_Request.objects.get(student=self.student)
    #     current_room = accommodation_request.room

        # # Nếu việc chuyển phòng đã được duyệt và phòng mới khác phòng hiện tại
        # if self.approved and current_room != self.room:
        #     # Giảm số người ở phòng cũ
        #     current_room.cur_people = max(current_room.cur_people - 1, 0)
        #     current_room.save()

        #     # Tăng số người ở phòng mới
        #     self.room.cur_people = min(self.room.cur_people + 1, self.room.sum_people)
        #     self.room.save()

        #     # Cập nhật phòng mới cho student trong Accomodation_Request
        #     accommodation_request.room = self.room
        #     accommodation_request.save()

        # super(RoomTransfer, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.student.first_name} - {self.room.room_name}"



class Guideline(models.Model):
    rule = models.TextField()
    guideline1 = models.CharField(max_length = 250)
    guideline2 = models.CharField(max_length = 250)
    guideline3 = models.CharField(max_length = 250)
    guideline4 = models.CharField(max_length = 250)
    guideline5 = models.CharField(max_length = 250)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.rule[:20]}"
class Rent(models.Model):
    room=models.CharField( max_length=50)
    rent = models.IntegerField()
    electricitybill = models.IntegerField()
    waterbill = models.IntegerField()
    service = models.IntegerField()
    def total_bill(self):
        return self.rent + self.electricitybill + self.waterbill + self.service

app_core/views.py
from django.shortcuts import *
from django.contrib.auth import authenticate, login as dlogin, logout as dlogout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import *
from django.http import JsonResponse


def welcome_page(request):
    rooms = Rooms.objects.all()
    for room in rooms:
        print(room.image1.url)
    context = {"rooms":rooms}
    return render(request, "home.html", context)


def login_page(request):
    context = {}
    return render(request, "login.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user is not None:
            dlogin(request, user)
            if username == "admin" or username == "admin_user":
                return redirect("admin-welcome-page")
            else:
                return redirect("welcome-page")
        messages.error(request, "Invalid Login Details")
        return redirect("login-page")
    else:
        return redirect("login-page")


def register_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = User.objects.create_user(username = username, password = password)
        user.save()
        return redirect("login-page")
    context = {}
    return render(request, "signup.html", context)


def view_rooms(request):
    rooms = Rooms.objects.all()
    context = {"rooms":rooms}
    return render(request, "view_rooms.html", context)


def logout_page(request):
    dlogout(request)
    return redirect("/")

def check_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

app_core/templates/student/complain.html
{% extends 'base.html' %}

{% block title %} Complain {% endblock %}

{% block content %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4 d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="container wow fadeIn">
        {% if is_student %}
        <br><br><br><br>
        <h2 class="my-5 h2 text-center text-primary">ACCOMODATION MANAGEMENT SYSTEM</h2>
        <hr>
        <h2 class="my-5 h2 text-center blue-text">Complain Form</h2>


        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:complaints' %}" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--firstName-->
                    <div class="md-form ">
                    <input type="text" id="first_name" class="form-control" name="first_name" value="{{student_user.first_name}}" disabled>
                    <label for="first_name" class="">First Name</label>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--lastName-->
                    <div class="md-form">
                    <input type="text" id="last_name" class="form-control" name="last_name" value="{{student_user.last_name}}" disabled>
                    <label for="last_name" class="">Last Name</label>
                    </div>

                </div>
                <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Username-->
                <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" value="{{request.user.username}}" aria-describedby="basic-addon1" disabled>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="subject" class="form-control" name="subject">
                    <label for="subject" class="">Subject</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                    <textarea type="text" id="message" class="form-control" name="message"> </textarea>
                    <label for="message" class="">Message</label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Lodge Complain</button>
                {% if messages %}
                <hr class="mb-1">
                  {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                  {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
        {% endif %}
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock content %}

app_core/templates/student/payment.html
{% extends 'base.html' %}

{% block title %} Payment {% endblock title %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4 d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center text-primary">ACCOMODATION MANAGEMENT SYSTEM</h2>
      <hr>
      <h2 class="my-5 h2 text-center blue-text">Deposit To Wallet</h2>


      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-12 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" method="POST" action="{% url 'app:payment' %}"> {% csrf_token %}
             <h4>{{request.user.username}}</h4>
              <hr>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="cc-name">Name on card</label>
                  <input type="text" class="form-control" id="cc-name" placeholder="" required name = "fullname">
                  <small class="text-muted">Full name as displayed on card</small>
                  <div class="invalid-feedback">
                    Name on card is required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="cc-number">Credit card number</label>
                  <input type="text" class="form-control" id="cc-number" placeholder="" required name = "card_number">
                  <div class="invalid-feedback">
                    Credit card number is required
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">Date Submit</label>
                  <input type="text" class="form-control" id="cc-date_submit" placeholder="14/10/2024" required name="date_submit">
                  <div class="invalid-feedback">
                    Please fill in Date submit
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">Bank</label>
                  <input type="text" class="form-control" id="cc-bank" placeholder="MB Bank, ViettinBank, Techcombank,...." required name = "bank">
                  <div class="invalid-feedback">
                    Please fill in Bank
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="amount">Amount</label>
                    <input type="text" class="form-control" required name="amount">
                  </div>
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to Deposit</button>
              {% if messages %}
              <hr class="mb-1">
                {% for message in messages %}
                  {% if message.tags == 'success' %}
                  <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                  {% else %}
                  <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                  {% endif %}
                {% endfor %}
              {% endif %}
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
<br><br><br><br><br><br><br><br>
{% endblock content %}

app_core/templates/student/student_dashboard.html
{% extends 'base.html' %}

{% block title %} StudentHome {% endblock title %}

{% block content %}

{% if is_student %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
        <div class="view" style="background-image: url('../../../media/photos/room1.png'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>@ Hostel Share</strong>
                </h1>

                <p>
                    <strong>Best & free Free accomodations for student </strong>
                </p>

                <p class="mb-4 d-none d-md-block">
                    <strong>All hostels recommended are clean and conducive for students.</strong>
                </p>
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
        <div class="view" style="background-image: url('../../../media/photos/room2.png'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
                <h1 class="mb-4">
                    <strong>Hostel Management</strong>
                </h1>

                <p class="mb-4 d-none d-md-block">
                    <strong>Modern rooms and many facilities</strong>
                </p>
            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
        <div class="view" style="background-image: url('../../../media/photos/room3.png'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
                <strong>Hostel For All</strong>
            </h1>

            <p>
                <strong>Dependable and Reliable Rooms For Students</strong>
            </p>

            </div>
            <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

        </div>
    </div>
    <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
    <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Facilities:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="">Recommended Rooms</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:room-transfer' %}">Room Transfer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:guest-stay' %}">Guest Stay</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:complaints' %}">LiveChat</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:payment' %}">Deposit</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:request-dashboard' %}">RequestsDashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:view-rents' %}">Rentall payment</a>
            </li>
        </ul>
        <!-- Links -->

        <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Wallet Balance: ${{student_user.wallet}}" aria-label="Search" disabled>
            </div>
        </form>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
        {% for room in rooms %}

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card image-->
            <div class="view overlay">
                <img src="{{room.image1.url}}" class="card-img-top" alt="" style="height:200px;">
                <a href="{% url 'app:room-details' room.id %}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'app:room-details' room.id %}" class="grey-text">
                <h5>{{room.room_name}}</h5>
                </a>
                <h5>
                <strong>
                    <a href="{% url 'app:room-details' room.id %}" class="dark-grey-text">Block {{room.block.block_name}}
                    <span class="badge badge-pill danger-color">{{room.room_tag}}</span>
                    </a>
                </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                    <strong>₦{{room.charge}}</strong>
                </h4>
            </div>
            <!--Card content-->

            </div>
            <!--Card-->
        </div>
        <!--Grid column-->

        {% endfor %}
        </div>
        <!--Grid row-->

    </section>
    <!--Section: Products v.3-->



    </div>
</main>
<!--Main layout-->

{% else %}
<br><br><br><br><br><br><br><br><br><br>
<div class="container card mb-5">
    <div class="mt-5">
        <h3 class="text-danger">You are not authorized to view this page until you register as a student of the school.</h3>
        <a href="{% url 'app:student-register'%}">Register Here</a>
    </div>
</div>

{% endif %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

app_core/templates/student/student_register.html
{% extends 'base.html' %}

{% block title %} Student Page {% endblock %}

{% block content %}
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">
        {% if is_student %}
        <!-- card body -->
        <div class="card card-body">
            <h5 class="text-success">You Already Registered For Studentship. Please Proceed To The<br>
                <strong class="p"> <a href="{% url 'app:student-dashboard' %}" class="waves-effect mt-3">Student Dashboard</a> </strong>
            </h5>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        {% else %}
        <!-- Heading -->
        <h2 class="my-5 h2 text-center text-primary">ACCOMODATION MANAGEMENT SYSTEM</h2>
        <hr>
        <h2 class="my-5 h2 text-center blue-text">Student Registration Form</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:student-register' %}" method="POST"> {% csrf_token %}

                <!--Grid row-->
                <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--firstName-->
                    <div class="md-form ">
                    <input type="text" id="first_name" class="form-control" name="first_name">
                    <label for="first_name" class="">First Name</label>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                    <!--lastName-->
                    <div class="md-form">
                    <input type="text" id="last_name" class="form-control" name="last_name">
                    <label for="last_name" class="">Last Name</label>
                    </div>

                </div>
                <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Username-->
                <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" value="{{request.user.username}}" aria-describedby="basic-addon1" disabled>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                <input type="text" id="email" class="form-control" name="email">
                <label for="email" class="">Email</label>
                </div>

                <!--matric-->
                <div class="md-form mb-5">
                <input type="text" id="matric_no" class="form-control" name="matric_no">
                <label for="matric_no" class="">Matric Number</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" name="address">
                <label for="address" class="">Address</label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Become  a Student</button>
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
        {% endif %}
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock content %}