MainProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app_core.views import *
from app_core.admin_views import *


urlpatterns = [

    path("admin/", admin.site.urls),
    path("", welcome_page, name="welcome-page"),
    path("admin_home", admin_home, name="admin-welcome-page"),
    path("login", login_page, name="login-page"),
    path("login_user", login_user, name="login-user"),
    path("logout_user", logout_page, name="logout-user"),
    path("register", register_page, name="register-user"),
    path("rooms", view_rooms, name="view-rooms"),
    path("app/", include("app_core.urls", namespace="app")),
    path('ajax/check-username/', check_username, name='check_username'),

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app_core/urls.py
from django.contrib import admin
from django.urls import path
from .student_views import *
from app_core.admin_views import *


app_name = "app"


urlpatterns = [

    # Students Urls
    
    path("student_dashboard", student_dashboard, name = "student-dashboard"),
    path("student_register", student_register, name = "student-register"),
    path("room_details/<str:room_id>", room_details, name = "room-details"),
    path("payment", payment, name = "payment"),
    path("accomodation_request", accomodation_request, name = "accomodation-request"),
    path("room_transfer", room_transfer, name = "room-transfer"),
    path("guest_stay", guest_stay, name = "guest-stay"),
    path("complain", complaints, name = "complaints"),
    path('rents', view_rents, name='view-rents'),
    
    # Admin Urls

    path("create_block", create_block, name = "create-block"),
    path("create_manager", create_manager, name = "create-manager"),
    path("create_room", create_room, name = "create-room"),
    path("manage_request", manage_request, name = "manage-request"),
    path("manage_transfer", manage_transfer, name = "manage-transfer"),
    path("manage_guest", manage_guest, name = "manage-guest"),
    path("manage_complaints", manage_complaints, name = "manage-complaints"),
    path("manage_rule", manage_rule, name = "manage-rule"),
    path("approve_or_disapprove/<str:ac_id>", approve_or_disapprove, name = "approve_or_disapprove"),
    path("complain_status/<str:complain_id>", complain_status, name = "complain_status"),
    path("guest_status/<str:guest_id>", guest_status, name = "guest_status"),
    path("transfer_status/<str:transfer_id>", transfer_status, name = "transfer_status"),
    path("request_dashboard", request_dashboard, name = "request-dashboard"),
    

]

app_core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.template.defaultfilters import truncatechars

class Student_Account(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    matric = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    is_student = models.BooleanField(default = True)
    wallet = models.IntegerField(default = 0, null = True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.user.username


class Deposit(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 200)
    card_number = models.CharField(max_length=20)
    bank = models.CharField(max_length = 6)
    date_submit = models.CharField(max_length = 100)
    amount = models.IntegerField()
    confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def save(self, *args, **kwargs):
        if self.pk:  # Kiểm tra nếu khoản tiền gửi đã tồn tại
            old_deposit = Deposit.objects.get(pk=self.pk)
            if old_deposit.confirm is False and self.confirm is True:  # Xác nhận lần đầu
                self.student.wallet += self.amount
                self.student.save()
        super().save(*args, **kwargs)  # Gọi phương thức save "thật"

    def __str__(self):
        return self.student.user.username


class House_Manager(models.Model):
    full_name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)
    phone_no = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.full_name


class Block(models.Model):
    house_manager = models.ForeignKey(House_Manager, on_delete = models.CASCADE)
    block_name = models.CharField(max_length = 50)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.block_name


class Rooms(models.Model):
    block = models.ForeignKey(Block, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=50, null=True)
    room_tag = models.CharField(max_length=10, default="NEW")
    description = models.TextField()
    condition = models.TextField()
    charge = models.IntegerField()
    slot_available = models.IntegerField(default=10) # tối đa 10 giường 
    is_available = models.BooleanField(default=True)
    image1 = models.ImageField(upload_to="photos")
    image2 = models.ImageField(upload_to="photos")
    image3 = models.ImageField(upload_to="photos")
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def short_description(self):
        return truncatechars(self.description, 20)
    def admin_photo(self):
        return mark_safe('<img src ="{}" width = 100 />'.format(self.image1.url))
    admin_photo.short_description = "Image"
    admin_photo.allow_tag = True
    def __str__(self):
        return self.room_name


class Accomodation_Request(models.Model):
    student = models.OneToOneField(Student_Account, on_delete = models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    approved = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)


    def __str__(self):
        return f"{self.room.room_name} has been {self.approved} {self.student.first_name}"



class Complaints(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    subject = models.CharField(max_length = 40)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.student.first_name} - {self.subject}"



class GuestStayRequest(models.Model):
    student = models.ForeignKey(Student_Account, on_delete = models.CASCADE)
    full_name = models.CharField(max_length = 40)
    address = models.CharField(max_length = 40)
    reason = models.TextField()
    status = models.BooleanField(default=False)
    date_from = models.DateField()
    date_to = models.DateField()
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.student.first_name} - {self.full_name}"


class RoomTransfer(models.Model):
    student = models.ForeignKey(Student_Account, on_delete=models.CASCADE)
    reason = models.TextField()
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE, related_name='new_room')  # phòng chuyển đến
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     # Lấy thông tin phòng hiện tại của sinh viên trước khi cập nhật
    #     accommodation_request = Accomodation_Request.objects.get(student=self.student)
    #     current_room = accommodation_request.room

        # # Nếu việc chuyển phòng đã được duyệt và phòng mới khác phòng hiện tại
        # if self.approved and current_room != self.room:
        #     # Giảm số người ở phòng cũ
        #     current_room.cur_people = max(current_room.cur_people - 1, 0)
        #     current_room.save()

        #     # Tăng số người ở phòng mới
        #     self.room.cur_people = min(self.room.cur_people + 1, self.room.sum_people)
        #     self.room.save()

        #     # Cập nhật phòng mới cho student trong Accomodation_Request
        #     accommodation_request.room = self.room
        #     accommodation_request.save()

        # super(RoomTransfer, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.student.first_name} - {self.room.room_name}"



class Guideline(models.Model):
    rule = models.TextField()
    guideline1 = models.CharField(max_length = 250)
    guideline2 = models.CharField(max_length = 250)
    guideline3 = models.CharField(max_length = 250)
    guideline4 = models.CharField(max_length = 250)
    guideline5 = models.CharField(max_length = 250)
    created_at = models.DateTimeField(auto_now = True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.rule[:20]}"
class Rent(models.Model):
    room=models.CharField( max_length=50)
    rent = models.IntegerField()
    electricitybill = models.IntegerField()
    waterbill = models.IntegerField()
    service = models.IntegerField()
    def total_bill(self):
        return self.rent + self.electricitybill + self.waterbill + self.service

app_core/views.py
from django.shortcuts import *
from django.contrib.auth import authenticate, login as dlogin, logout as dlogout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import *
from django.http import JsonResponse


def welcome_page(request):
    rooms = Rooms.objects.all()
    for room in rooms:
        print(room.image1.url)
    context = {"rooms":rooms}
    return render(request, "home.html", context)


def login_page(request):
    context = {}
    return render(request, "login.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password = password)
        if user is not None:
            dlogin(request, user)
            if username == "admin" or username == "admin_user":
                return redirect("admin-welcome-page")
            else:
                return redirect("welcome-page")
        messages.error(request, "Invalid Login Details")
        return redirect("login-page")
    else:
        return redirect("login-page")


def register_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = User.objects.create_user(username = username, password = password)
        user.save()
        return redirect("login-page")
    context = {}
    return render(request, "signup.html", context)


def view_rooms(request):
    rooms = Rooms.objects.all()
    context = {"rooms":rooms}
    return render(request, "view_rooms.html", context)


def logout_page(request):
    dlogout(request)
    return redirect("/")

def check_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

app_core/templates/admin_templates/admin_home.html
{% extends 'admin_templates/base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

<br><br><br><br> 
<!--Main layout-->
<main>
    <div class="container">

    {% include 'admin_templates/admin_nav.html' %}

    <h2 class="my-5 h2 text-center">Room Requests</h2>
        <div class="table">
            <table class="table-stripped table-hovered table-bordered">
                <thead>
                    <tr>
                        <td>Accomodation ID</td>
                        <td>Student ID</td>
                        <td>Student Name</td>
                        <td>Student Username</td>
                        <td>Room ID</td>
                        <td>Room Name</td>
                        <td>Block Name</td>
                        <td>House Manager</td>
                        <td>Date</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    {% for request in requestss %}
                    <tr>
                        <td>{{request.id}}</td>
                        <td>{{request.student.id}}</td>
                        <td>{{request.student.first_name}} - {{request.student.last_name}}</td>
                        <td>{{request.student.user.username}}</td>
                        <td>{{request.room.id}}</td>
                        <td>{{request.room.room_name}}</td>
                        <td>{{request.room.block.block_name}}</td>
                        <td>{{request.room.block.house_manager.full_name}}</td>
                        <td>{{request.created_at}}</td>
                        {% if request.approved %}
                        <td><a href="{% url 'app:approve_or_disapprove' request.id %}" type="button" class="btn btn-danger">Disapprove</a></td>
                        {% else %}
                        <td><a href="{% url 'app:approve_or_disapprove' request.id %}" type="button" class="btn btn-success">Approve</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/admin_nav.html
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Management:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin-welcome-page' %}">ManageRequests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-transfer' %}">ManageTransfers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-guest' %}">ManageGuests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-complaints' %}">ManageComplaints</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:manage-rule' %}">ManageRules</a>
                </li>
            </ul>

        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

app_core/templates/admin_templates/create_block.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateBlock  {% endblock %}


{% block content %} 
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Block</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-block' %}" method="POST"> {% csrf_token %}
                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="block_name" class="form-control" name="block_name">
                    <label for="block_name" class="">Block Name</label>
                </div>

                
                <!--address-->
                <div class="md-form mb-5">
                    <select id="room_option" class="form-control" name="house_manager">
                        <option>Choose Manager</option>
                        {% for manager in house_managers %}
                            <option value="{{manager.id}}"> {{manager.full_name}} | Email {{manager.email}} | Address {{manager.address}}</option>
                        {% endfor %}
                    </select>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Block</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/create_manager.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateManager  {% endblock %}


{% block content %} 
<br>
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Manager</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-manager' %}" method="POST"> {% csrf_token %}
                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="full_name" class="form-control" name="full_name">
                    <label for="full_name" class="">Full Name</label>
                </div>

                <!--email-->
                <div class="md-form mb-5">
                    <input type="text" id="email" class="form-control" name="email">
                    <label for="email" class="">Email</label>
                </div>

                <!--matric-->
                <div class="md-form mb-5">
                    <input type="text" id="phone_no" class="form-control" name="phone_no">
                    <label for="phone_no" class="">Phone Number</label>
                </div>

                <!--address-->
                <div class="md-form mb-5">
                    <input type="text" id="address" class="form-control" name="address">
                    <label for="address" class="">Address</label>
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Manager</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
<br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/create_room.html
{% extends 'admin_templates/base.html' %}

{% block title %} CreateRoom  {% endblock %}

{% block content %} 
<!--Main layout-->
<main class="mt-4 pt-4">
    <div class="container wow fadeIn">

        <!-- Heading -->
        <br><br>
        <h2 class="my-5 h2 text-center text-primary">Create Room</h2>

        <!--Grid row-->
        <div class="row">

        <!--Grid column-->
        <div class="col-md-11 mb-4">

            <!--Card-->
            <div class="card">

            <!--Card content-->
            <form class="card-body" action="{% url 'app:create-room' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}

                <!--ame-->
                <div class="md-form mb-5">
                    <input type="text" id="room_name" class="form-control" name="room_name">
                    <label for="room_name" class="">Room Name</label>
                </div>

                <!--tag-->
                <div class="md-form mb-5">
                    <input type="text" id="room_tag" class="form-control" name="room_tag">
                    <label for="room_tag" class="">Room Tag</label>
                </div>

                <!--description-->
                <div class="md-form mb-5">
                    <input type="text" id="room_description" class="form-control" name="room_description">
                    <label for="room_description" class="">Room Description</label>
                </div>

                <!--charge-->
                <div class="md-form mb-5">
                    <input type="text" id="room_charge" class="form-control" name="room_charge">
                    <label for="room_charge" class="">Room Charge</label>
                </div>

                <div class="md-form mb-5">
                    <input type="text" id="room_condition" class="form-control" name="room_condition">
                    <label for="room_condition" class="">Room Condition</label>
                </div>

                <!--block-->
                <div class="md-form mb-5">
                    <select id="room_option" class="form-control" name="block_name">
                        <option>Choose Block</option>
                        {% for block in blocks %}
                            <option value="{{block.id}}">Block {{block.block_name}} | Manager {{block.hostel_manager.full_name}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image1" class="form-control" name="image1">
                    <!-- <label for="image1" class="">Image One</label> -->
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image2" class="form-control" name="image2">
                    <!-- <label for="image2" class="">Image Two</label> -->
                </div>

                <div class="md-form mb-5">
                    <input type="file" id="image3" class="form-control" name="image3">
                    <!-- <label for="image3" class="">Image Three</label> -->
                </div>

                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Create Room</button>
                {% if messages %}
                    <hr class="mb-1">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <span class="btn btn-success btn-lg btn-block" type="button">{{message}}</span>
                    {% else %}
                    <span class="btn btn-danger btn-lg btn-block" type="button">{{message}}</span>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </form>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->

        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
{% endblock %}

app_core/templates/admin_templates/manage_complaint.html
{% extends 'admin_templates/base.html' %}

{% block title %} ManageComplaint {% endblock %}

{% block content %}

<br><br><br><br> 
<!--Main layout-->
<main>
    <div class="container">

    {% include 'admin_templates/admin_nav.html' %}

    <h2 class="my-5 h2 text-center">Manage Complaints</h2>
        <div class="table">
            <table class="table-stripped table-hovered table-bordered">
                <thead>
                    <tr>
                        <td>Complaint ID</td>
                        <td>Student ID</td>
                        <td>Student Name</td>
                        <td>Student Username</td>
                        <td>Subject</td>
                        <td>Message</td>
                        <td>Action</td>
                        <td>Date</td>
                    </tr>
                </thead>
                <tbody>
                    {% for complain in complaints %}
                    <tr>
                        <td>{{complain.id}}</td>
                        <td>{{complain.student.id}}</td>
                        <td>{{complain.student.first_name}} - {{complain.student.last_name}}</td>
                        <td>{{complain.student.user.username}}</td>
                        <td>{{complain.subject}}</td>
                        <td>{{complain.message}}</td>
                        {% if complain.status %}
                        <td><a href="{% url 'app:complain_status' complain.id %}" type="button" class="btn btn-danger">Not Treated</a></td>
                        {% else %}
                        <td><a href="{% url 'app:complain_status' complain.id %}" type="button" class="btn btn-success">Treated</a></td>
                        {% endif %}
                        <td>{{complain.created_at}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/manage_guest.html
{% extends 'admin_templates/base.html' %}

{% block title %} ManageGuest {% endblock %}

{% block content %}

<br><br><br><br> 
<!--Main layout-->
<main>
    <div class="container">
    {% include 'admin_templates/admin_nav.html' %}
    <h2 class="my-5 h2 text-center">Manage Guest Requests</h2>
        <div class="table">
            <table class="table-stripped table-hovered table-bordered">
                <thead>
                    <tr>
                        <td>Guest ID</td>
                        <td>Guest Fullname</td>
                        <td>Guest Address</td>
                        <td>Student ID</td>
                        <td>Student Name</td>
                        <td>Reason</td>
                        <td>Date From</td>
                        <td>Date To</td>
                        <td>Action</td>
                        <td>Date Created</td>
                    </tr>
                </thead>
                <tbody>
                    {% for guest in guests %}
                    <tr>
                        <td>{{guest.id}}</td>
                        <td>{{guest.full_name}}</td>
                        <td>{{guest.address}}</td>
                        <td>{{guest.student.id}}</td>
                        <td>{{guest.student.first_name}} - {{guest.student.last_name}}</td>
                        <td>{{guest.reason}}</td>
                        <td>{{guest.date_from}}</td>
                        <td>{{guest.date_to}}</td>
                        {% if guest.status %}
                        <td><a href="{% url 'app:guest_status' guest.id %}" type="button" class="btn btn-danger">Disapprove</a></td>
                        {% else %}
                        <td><a href="{% url 'app:guest_status' guest.id %}" type="button" class="btn btn-success">Approve</a></td>
                        {% endif %}
                        <td>{{guest.created_at}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

app_core/templates/admin_templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar bg-custom">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'admin-welcome-page' %}">
        <strong class="text-primary">AMS</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'admin-welcome-page' %}"><b>Dashboard</b></a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-block' %}"><b>Create Block</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-manager' %}"><b>Create Manager</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'app:create-room' %}"><b>Create Room</b></a>
          </li>
          {% endif %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'logout-user' %}" class="nav-link border border-light rounded waves-effect">
              <b class="text-danger mr-2">Logout</b>[<i class="fas fa-user mr-2"> {{ request.user.username}}] </i>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'login-page' %}"><b>Login</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'register-user' %}"><b>Register</b></a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
  